### ISSUE TITLE
address property and registeredAddress used in other EU core vocs

### ISSUE THREAD

**Issue by giorgialodi** [SEMICeu/Core-Location-Vocabulary#8]
if you define here the address property you may also want to define the property registeredAddress, which is used in  CPV, CPOV and Core Business Voc,. as sub property of the generic address. It would make sense; however, as it is currently modelled in CLV you cannot because the domain of address is Location not owl:Thing (and Person, or Public organisation or Legal Entity are not locations but agents).
What I am saying is that if you say that a resource or a thing has address and geometry you may also say that a thing has a  specific type of address that is the registeredAddress and used it in the other vocabularies (with prefix clv).

**Comment by mayaborges** [comment]
There may be a need to differentiate between physical addresses, which are those locations have, and postal addresses, which are those people and organisations have, and which would include poBoxes. The current modelling implies that a Location can have a poBox as part of its address, which does not seem correct. Meanwhile a poBox can (at least in Denmark) move its physical location (within one postal code) without changing the postal address.

Contributed by aaing@digst.dk, maybo@digst.dk

**Comment by bertvannuffelen** [comment]
I understand the need for this distinction but the question if these distinctive roles of addresses can be captured in the core vocabularies. E.g. using addresses to identify a physical location is vulnerable to many administrative changes. E.g. relabeling happens because cities merge, streets get renamed, or a renumbering happens. 

Today 2 role address properties exits in the core vocabularies:
   - address (locn:address): an address for an entity
   - registered address (http://www.w3.org/ns/legal#registeredAddress) : an address that has been registered in some official place.

Is there need for another role-address property? E.g. locn:address be used to express a physical addresses. But of-course one cannot distinguish then between contact-address and phyical-address.

**Comment by EmidioStani** [comment]
During the webinar of 02/12/201 it was agreed to move registeredAddress in Core Location

**Comment by EmidioStani** [comment]
The registered address has been moved: https://semiceu.github.io/Core-Location-Vocabulary/releases/2.00/
